#User Authentication / Authorization Test
#sign - login - token generate - token reissuance - logout/token delete

###
POST http://localhost:8080/sign
Content-Type: application/json

< ./test-file/user1.json
###
POST http://localhost:8080/login
Content-Type: application/json

< ./test-file/login-user1.json
# < ./test-file/login-user2.json
###
POST http://localhost:8080/token_check
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjU0NjUyOTcwLCJleHAiOjE2NTQ2NTQ3NzB9.D1nnt0LDqtSXURikVMbksqK5pXmmXj1YC-vb0DyUU6rmL3AbYCo-9qSRvNFG3o-mG7_WSK-ad7DO3rc3KyuWCQ

###
POST http://localhost:8080/token_check
Authorization: Refresh

###
POST http://localhost:8080/my/logout
Authorization: Bearer
Content-Type: application/json

> ./test-file/logout-user1.json
###
GET http://localhost:8080/api/board/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzQGV4YW1wbGUuY29tIiwiaWF0IjoxNjU0NjUyOTcwLCJleHAiOjE2NTQ2NTQ3NzB9.D1nnt0LDqtSXURikVMbksqK5pXmmXj1YC-vb0DyUU6rmL3AbYCo-9qSRvNFG3o-mG7_WSK-ad7DO3rc3KyuWCQ